config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orders, only: %i[index show]
  resources :slots, only: %i[index]
  root "orders#index"
end

app/models/application_record.rb
# frozen_string_literal: true

# Base application model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :orders, dependent: :restrict_with_error

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :address, presence: true
end

app/models/order.rb
# frozen_string_literal: true

# Customer order
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :customer, presence: true
  validates :delivery_time, presence: true
  validates :product, presence: true
  validates :status, presence: true

  enum status: { todo: 0, delivered: 1 }

  scope :to_prepare, ->(datetime) { where(delivery_time: datetime + 1.hour) }
  scope :by_product, ->(product_id) { where(product_id: product_id) }

  FIRST_DELIVERY_HOUR = 8
  LAST_DELIVERY_HOUR = 19

  delegate :name, to: :product, prefix: true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :orders, dependent: :restrict_with_error

  validates :name, presence: true
  validates :price, numericality: true, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# Controller for listing and showing all Orders
class OrdersController < ApplicationController
  def index
    set_date
    @orders = Order.includes(:customer, :product)
                   .where(Order.arel_table[:delivery_time].gteq(@date.beginning_of_day))
                   .where(Order.arel_table[:delivery_time].lteq(@date.end_of_day))
                   .order(:delivery_time)
  end

  def show
    set_order
  end

  private

  def set_date
    @date = if params[:date]
              Date.parse(params[:date])
            else
              Date.current
            end
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/slots_controller.rb
# frozen_string_literal: true

# Controller for viewing slots
class SlotsController < ApplicationController
  def index
    set_date
  end

  private

  def set_date
    @date = if params[:date]
              Date.parse(params[:date]).beginning_of_week
            else
              Date.current.beginning_of_week
            end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application helper
module ApplicationHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

# Orders helper
module OrdersHelper
end

app/helpers/slots_helper.rb
# frozen_string_literal: true

# Slots helper
module SlotsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bergamotte
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    %nav
      %strong
        = link_to "Orders", orders_path
        |
        = link_to "Slots", slots_path

    %hr/

    = yield

app/views/orders/index.html.haml
%p#notice= notice

%h1
  Orders for #{@date}

%div
  = link_to "Previous Date", orders_path(date: @date - 1.day)
  |
  = link_to "Next Date", orders_path(date: @date + 1.day)

%hr/

- if @orders.any?
  %table
    %thead
      %tr
        %th Delivery time
        %th Status
        %th Customer
        %th Product
        %th Price
        %th
    %tbody
      - @orders.each do |order|
        %tr
          %td= order.delivery_time
          %td= order.status
          %td= order.customer.name
          %td= order.product_name
          %td= number_to_currency order.product.price
          %td= link_to 'Show', order
- else
  %h4 No orders for this day

app/views/orders/show.html.haml
%p#notice= notice

%p
  %strong Delivery time:
  = @order.delivery_time

%p
  %strong Status:
  = @order.status

%p
  %strong Product:
  = @order.product_name

%p
  %strong Customer:
  = @order.customer.name

%p
  %strong Address:
  = @order.customer.address

= link_to 'Back', orders_path(date: @order.delivery_time.to_date)

app/views/slots/index.html.haml
%h1
  Slots overview for week starting #{@date}

%div
  = link_to "Previous Week", slots_path(date: @date - 1.week)
  |
  \#{link_to "Next Week", slots_path(date: @date + 1.week)}

%hr/

%table
  %thead
    %tr
      %th
        Hour
      - [*@date.beginning_of_week..@date.end_of_week].each do |date|
        %th= date
  %tbody
    - [*Order::FIRST_DELIVERY_HOUR..Order::LAST_DELIVERY_HOUR].each do |hour|
      %tr
        %th= hour
        - [*@date.beginning_of_week..@date.end_of_week].each do |date|
          %td
            - Order.to_prepare(date.to_datetime.change(hour: hour - 1)).map { |order| [order.product.id,
              order.product.name] }.sort { |a, b| a[1] <=> b[1] }.uniq.each do |products|
              = "#{Product.find(products[0]).name}"
              = "#{Order.to_prepare(date.to_datetime.change(hour: hour - 1)).by_product(products[0]).length}"
              %br